language: node_js
node_js:
  - "0.10"
before_script:
  - sudo apt-get install fontforge
  - npm install -g grunt-cli

  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get -qq install g++-4.8
  - git clone https://github.com/google/woff2.git
  - cd woff2
  - git submodule init
  - git submodule update
  - make clean all
  - export PATH=$PWD:$PATH
  - echo $PATH
  - cd ..
